config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :philosophers do
    resources :reviews, only: [ :new, :create ]
    resources :bookings, only: [ :new, :create, :destroy ]
  end
	get'/dashboard', to: "users#dashboard"
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    Classical philosophers also <i class="fas fa-heart"></i> social media!
  </div>
  <div class="footer-links list-inline">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://image.flaticon.com/icons/svg/570/570631.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active mr-5 search-bar">

        <%= form_tag philosophers_path, method: :get do %>
          <%= text_field_tag :query, params[:query] %>
          <%= submit_tag "search", class: "btn btn-secondary" %>
        <% end %>

      </li>
      <li class="nav-item active">
        <%= link_to "Home", "/", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Philosophers", philosophers_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= image_tag "https://image.flaticon.com/icons/svg/647/647573.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", dashboard_path, class: "dropdown-item" %>
            <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>