config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :philosophers do
    resources :reviews, only: [ :new, :create ]
    resources :bookings, only: [ :new, :create, :destroy ]
  end
	get'/dashboard', to: "users#dashboard"
end

app/models/philosopher.rb
class Philosopher < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :quote, presence: true
  validates :worth, presence: true
  validates :currency, presence: true
  include PgSearch::Model
  pg_search_scope :search_by_name_and_quote,
    against: [ :name, :quote ],
    using: {
      tsearch: { prefix: true } 
    }
end

app/controllers/philosophers_controller.rb
class PhilosophersController < ApplicationController
    before_action :set_philosopher, only: [:show, :edit, :update, :destroy]
    skip_before_action :authenticate_user!, only: [:index, :show] 
    
    def index
        if params[:query].present?
           @philosophers = Philosopher.search_by_name_and_quote(params[:query])
        else
           @philosophers = Philosopher.all
        end
    end

    def show
        # @philosopher = Philosopher.find(params[:id])
        @booking = Booking.new
    end

    def new
        @philosopher = Philosopher.new
    end

    def create
        @philosopher = Philosopher.new(philosopher_params)
        current_user.role = "agent"
        current_user.save
        @philosopher.user_id = current_user.id
        if @philosopher.save
            flash[:notice] ="🎉 Thank you for letting #{@philosopher.name} provide wisdom to others!🦉"
            redirect_to philosopher_path(@philosopher)
          else
            render 'new'
        end
    end

    def edit
    end

    def update
        @philosopher.update(philosopher_params)
        if @philosopher.save
            redirect_to philosophers_path
          else
            render :new
        end
    end

    def destroy
        @philosopher.destroy
        redirect_to new_philosopher_path
    end

    private
    def philosopher_params
        params.require(:philosopher).permit(:id, :name, :quote, :worth, :currency)
    end

    def set_philosopher
        @philosopher = Philosopher.find(params[:id])
    end
end

app/views/philosophers/edit.html.erb
<%= simple_form_for @philosopher do |element| %>
  <%= element.input :name %>
  <%= element.input :quote %>
  <%= element.input :worth %>
  <%= element.input :currency %>
  <div class="text-center  my-5">
    <%= element.submit class: "btn btn-secondary btn-lg" %>
    <%= link_to "Return", philosophers_path, class: "btn btn-secondary btn-lg" %>
  </div>
<% end %>

app/views/philosophers/index.html.erb
<div class="container">
  
  <div class="row opener text-center justify-content-center">
    <div class="col-8">
     <h1 class="index-quote">Those who know, do. <br> Those that understand, teach.</h1>
     <br>
     <p>Book some time with one of the famous Greek Philosophers right out of golden age!</p>  
    </div>
  </div>

  <div class="row justify-content-center align-items-center">
    <div class="cards mb-5 w-100">
      <% @philosophers.each do |philosopher| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.imgur.com/OELHk5p.jpg)">
          <%= link_to "#{philosopher.name}", "/philosophers/#{philosopher.id}", class: "text-center" %>
        </div>
      <% end %>
    </div>
  </div>
</div>




  

<%# if philosopher.photo.attached?  %>
<%#=  cl_image_tag philosopher.photo.key, width: 348, height: 124, class: "card-img-top" %>
<%# end %>

app/views/philosophers/new.html.erb
<div class="container mt-3">

  <%= simple_form_for @philosopher do |f| %>
    <%= f.input :name %>
    <%= f.input :quote %>
    <%= f.input :worth %>
    <%= f.input :currency %>

    <%= f.submit class: "btn btn-secondary btn-lg text-center" %>

  <% end %>

  <%= link_to "Return", "/philosophers" %>

</div>

app/views/philosophers/show.html.erb
<div class="container mt-3">

  <div class="card-product">
    <img src="https://i.imgur.com/OELHk5p.jpg" />

    <%#=  cl_image_tag @philosopher.photo.key, width: 348, height: 124, class: "card-img-top mb-3" %>

    <div class="card-product-infos">
      <h3><%= "'#{@philosopher.quote}'"  %></p>
      <h2><%= "- #{@philosopher.name}" %></h2>
      <p class="card-text">Agent: <%= @philosopher.user.name %></p>
      <%= link_to "Reserve #{@philosopher.name}", new_philosopher_booking_path(@philosopher), class: "btn btn-secondary btn-lg m-5" %>
      <h2 class = "card-text">Price: <%= @philosopher.worth %> <%= @philosopher.currency.pluralize %> per day💰</h3>
    </div>
  </div>

  <div class="philosopher-btns m-5">

    <% if user_signed_in? && current_user.email == @philosopher.user.email %>    

    <%= link_to "Edit #{@philosopher.name}", edit_philosopher_path, class: "btn btn-secondary btn-lg text-center m-1" %>

    <%= link_to "Leave a Review", new_philosopher_review_path(@philosopher), class: "btn btn-secondary btn-lg text-center m-1" %>

    <%= link_to "Return", "/", class: "btn btn-secondary btn-lg text-center m-1" %>

    <% else %>

    <%= link_to "Leave a Review", new_philosopher_review_path(@philosopher), class: "btn btn-secondary btn-lg text-center m-1" %>

    <%= link_to "Return", "/", class: "btn btn-secondary btn-lg text-center m-1" %>

    <% end %>


  </div>

  <div class="card-product">

    <%#=  cl_image_tag @philosopher.photo.key, width: 348, height: 124, class: "card-img-top mb-3" %>

    <div class="card-product-infos">
      <h3>Reviews</h3>
      <div class="overflow-auto">
        <% if @philosopher.reviews.empty? %>
          <p>Be the first to leave a review 🐣</p>
        <%else %>
          <ul class="list-group w-100">
            <% @philosopher.reviews.each do |review| %>
              
              <li class="list-group-item border-0 d-flex justify-content-between align-items-center">
                <div>
                  <span class="badge badge-primary badge-pill" style="background: white">
                    <% counter = 0 %>
                    <% 5.times do %>
                      <i class="fa <%=review.rating > counter ? 'fa-star' : 'fa-star-o' %>" style="color: #f4511e"></i>
                      <% counter += 1 %>
                    <% end %>
                  </span>
                  <strong>
                    <%= "by #{review.user.name} - " %>
                  </strong>
                  <%= "'#{review.content}'" %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>

  
</div>
</div>